version: '3'
services:
  postgresdb:
    image: postgis/postgis
    container_name: linkey-postgres
    ports:
      - 5434:5432 
    volumes:
      - linkey-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: linkey

volumes:
  linkey-postgres: